### ISSUE TITLE
consider merging with jshint-rb

### ISSUE THREAD

**Issue by josephholsten** [StupidCodeFactory/jshint_ruby#1]
I'm trying to start maintaining a fork of jshint_on_rails at https://github.com/josephholsten/jshint.rb

I'm not really attached to the implementation, I'd just like to make sure there is at least one well-maintained jshint to ruby adapter.

**Comment by StupidCodeFactory** [comment]
Hi @josephholsten,

This a perfectly reasonable concern.
The only purpose of this gem is to provide access to the source from ruby. 
I want to keep it decoupled from any other implementation concerns, i.e the process of linting allowing different implementations for different context.
May be jshint.rb could depend on this gem to include the jshint sources?

**Comment by josephholsten** [comment]
I see. I'll spike deferring the actual exec out to you.

If `jshint_ruby` is just a minimal wrapper, would you consider having your gem version be identical to the version of jshint you package?

Do you have any other goals for `jshint_ruby`?

**Comment by StupidCodeFactory** [comment]
i was thinking about following the jshint version which would make sense.

**Comment by StupidCodeFactory** [comment]
not sure which other goals i may have for it? But i'd be really happy to collaborate or evolve it further
